"""Initial migration

Revision ID: 1601908f02c8
Revises: a4268b57ce16
Create Date: 2026-03-27 04:21:39.873634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '1601908f02c8'
down_revision: Union[str, Sequence[str], None] = 'a4268b57ce16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


enum_name = 'progressstatus'

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Сначала создаём ENUM тип
    op.execute(f"CREATE TYPE {enum_name} AS ENUM('started', 'completed')")

    # 2. Добавляем колонку с созданным ENUM типом
    op.add_column('progress',
                  sa.Column('status',
                            ENUM('started', 'completed', name=enum_name, create_type=False),
                            nullable=True))
    op.create_foreign_key(None, 'progress', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'progress', 'users', ['user_id'], ['id'])
    op.drop_column('progress', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.drop_column('progress', 'status')
    # ### end Alembic commands ###
